"""Added ProjectEvent model

Revision ID: 11d6a165138
Revises: 17f8e1dd6d4
Create Date: 2015-04-27 15:53:51.274920

"""

# revision identifiers, used by Alembic.
revision = '11d6a165138'
down_revision = '17f8e1dd6d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('human_text', sa.Text(), nullable=True),
    sa.Column('optional_data_json', sa.Text(), nullable=True),
    sa.Column('optional_event_type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_event')
    ### end Alembic commands ###
