"""Added Project.{local_repo_exists,build_is_running} columns

Revision ID: 15eeead3051
Revises: 480d764b328
Create Date: 2015-04-27 23:56:03.619622

"""

# revision identifiers, used by Alembic.
revision = '15eeead3051'
down_revision = '480d764b328'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('build_is_running', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('local_repo_exists', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'local_repo_exists')
    op.drop_column('project', 'build_is_running')
    ### end Alembic commands ###
