"""Added LinkedCopr model

Revision ID: 17f8e1dd6d4
Revises: 17383200dec
Create Date: 2015-04-24 15:17:42.155579

"""

# revision identifiers, used by Alembic.
revision = '17f8e1dd6d4'
down_revision = '17383200dec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_copr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('coprname', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linked_copr')
    ### end Alembic commands ###
