"""Added Project column: dockerhub_build_status_updated_on_local_time

Revision ID: 1c4d761a9c1
Revises: 55dd2103ae6
Create Date: 2015-06-16 11:48:41.154433

"""

# revision identifiers, used by Alembic.
revision = '1c4d761a9c1'
down_revision = '55dd2103ae6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('dockerhub_build_status_updated_on_local_time', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'dockerhub_build_status_updated_on_local_time')
    ### end Alembic commands ###
