"""added columnt to Project delete_requested_on

Revision ID: 1dc5637f291
Revises: 345223ef6c1
Create Date: 2015-06-19 16:47:17.833646

"""

# revision identifiers, used by Alembic.
revision = '1dc5637f291'
down_revision = '345223ef6c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('delete_requested_on', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_project_delete_requested_on'), 'project', ['delete_requested_on'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_delete_requested_on'), table_name='project')
    op.drop_column('project', 'delete_requested_on')
    ### end Alembic commands ###
