"""Added User table

Revision ID: 2478cbe8b3f
Revises: None
Create Date: 2015-04-14 21:43:11.508912

"""

# revision identifiers, used by Alembic.
revision = '2478cbe8b3f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('mail', sa.String(length=150), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
