"""Added default value for Project.source_mode 2

Revision ID: 257ba619bb7
Revises: 34be3989771
Create Date: 2015-04-21 14:20:12.619328

"""

# revision identifiers, used by Alembic.
revision = '257ba619bb7'
down_revision = '34be3989771'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
