"""added columnt to Project dh_start_requested_on dh_start_done_on

Revision ID: 345223ef6c1
Revises: ed7a32e6f3
Create Date: 2015-06-18 16:28:21.367078

"""

# revision identifiers, used by Alembic.
revision = '345223ef6c1'
down_revision = 'ed7a32e6f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('dh_start_done_on', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('dh_start_requested_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'dh_start_requested_on')
    op.drop_column('project', 'dh_start_done_on')
    ### end Alembic commands ###
