"""Added default value for Project.source_mode

Revision ID: 34be3989771
Revises: 3841e8a890c
Create Date: 2015-04-21 14:18:55.012213

"""

# revision identifiers, used by Alembic.
revision = '34be3989771'
down_revision = '3841e8a890c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
