"""Added Project.title column

Revision ID: 356becdf6cb
Revises: f4d5208770
Create Date: 2015-04-17 15:26:11.724628

"""

# revision identifiers, used by Alembic.
revision = '356becdf6cb'
down_revision = 'f4d5208770'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('title', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'title')
    ### end Alembic commands ###
