"""Added created_on, updated_on  columns

Revision ID: 3841e8a890c
Revises: 356becdf6cb
Create Date: 2015-04-21 12:06:09.847342

"""

# revision identifiers, used by Alembic.
revision = '3841e8a890c'
down_revision = '356becdf6cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_on')
    op.drop_column('user', 'created_on')
    op.drop_column('project', 'updated_on')
    op.drop_column('project', 'created_on')
    ### end Alembic commands ###
