"""Added Project columns: dockerhub_build_status[_updated_on]

Revision ID: 4bee4bbb00f
Revises: 9cd64c954c
Create Date: 2015-04-29 17:39:42.325249

"""

# revision identifiers, used by Alembic.
revision = '4bee4bbb00f'
down_revision = '9cd64c954c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('dockerhub_build_status', sa.String(length=32), nullable=True))
    op.add_column('project', sa.Column('dockerhub_build_status_updated_on', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'dockerhub_build_status_updated_on')
    op.drop_column('project', 'dockerhub_build_status')
    ### end Alembic commands ###
