"""Added Project columns: dockerhub_latest_build_{started,updated}_on, removed dockerhub_build_status_updated_on

Revision ID: 55dd2103ae6
Revises: 4bee4bbb00f
Create Date: 2015-05-22 13:17:34.964764

"""

# revision identifiers, used by Alembic.
revision = '55dd2103ae6'
down_revision = '4bee4bbb00f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('dockerhub_latest_build_started_on', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('dockerhub_latest_build_updated_on', sa.DateTime(), nullable=True))
    op.drop_column('project', 'dockerhub_build_status_updated_on')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('dockerhub_build_status_updated_on', sa.VARCHAR(length=32), nullable=True))
    op.drop_column('project', 'dockerhub_latest_build_updated_on')
    op.drop_column('project', 'dockerhub_latest_build_started_on')
    ### end Alembic commands ###
