"""Added Project datetime columns related to commit/push/build process

Revision ID: 9cd64c954c
Revises: 15eeead3051
Create Date: 2015-04-29 13:16:19.442145

"""

# revision identifiers, used by Alembic.
revision = '9cd64c954c'
down_revision = '15eeead3051'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('build_started_on', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('local_repo_changed_on', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('local_repo_pushed_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'local_repo_pushed_on')
    op.drop_column('project', 'local_repo_changed_on')
    op.drop_column('project', 'build_started_on')
    ### end Alembic commands ###
