"""Change column type to datetime : dockerhub_build_status_updated_on_local_time

Revision ID: ed7a32e6f3
Revises: 1c4d761a9c1
Create Date: 2015-06-16 14:38:46.839774

"""

# revision identifiers, used by Alembic.
revision = 'ed7a32e6f3'
down_revision = '1c4d761a9c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'dockerhub_build_status_updated_on_local_time',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.DateTime(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'dockerhub_build_status_updated_on_local_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    ### end Alembic commands ###
