"""Added Project table

Revision ID: f4d5208770
Revises: 2478cbe8b3f
Create Date: 2015-04-15 14:16:00.040247

"""

# revision identifiers, used by Alembic.
revision = 'f4d5208770'
down_revision = '2478cbe8b3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_mode', sa.String(length=40), nullable=True),
    sa.Column('local_text', sa.Text(), nullable=True),
    sa.Column('git_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    ### end Alembic commands ###
